services:
  caddy:
    environment:
      - CADDY_WAF_IP_BLACKLIST_FILE=/etc/caddy/waf/crawler-ip-blacklist.txt.example
      - CADDY_WAF_IP_WHITELIST_FILE=/etc/caddy/waf/bandwidth-quota-whitelist.txt.example
      - CADDY_WAF_DNS_BLACKLIST_FILE=/etc/caddy/waf/dns-blacklist.txt.example
      - CADDY_BANDWIDTH_QUOTA_WHITELIST_FILE=/etc/caddy/waf/bandwidth-quota-whitelist.txt.example
  vector:
    environment:
      VECTOR_ORG: sjtug
      VECTOR_SERVER: ci
    volumes:
      - "./caddy/repositories.local.csv:/etc/vector/repositories.csv:ro"
  lug:
    volumes:
      - "./lug/config.local.yaml:/config.local.yaml:ro"
    command: -c /config.local.yaml
