services:
  caddy:
    build:
      args:
        - USE_GOPROXY=false
    environment:
      - CADDY_WAF_IP_BLACKLIST_FILE=/etc/caddy/waf/crawler-ip-blacklist.txt.example
      - CADDY_WAF_IP_WHITELIST_FILE=/etc/caddy/waf/bandwidth-quota-whitelist.txt.example
      - CADDY_WAF_DNS_BLACKLIST_FILE=/etc/caddy/waf/dns-blacklist.txt.example
      - CADDY_BANDWIDTH_QUOTA_WHITELIST_FILE=/etc/caddy/waf/bandwidth-quota-whitelist.txt.example
  vector:
    environment:
      VECTOR_ORG: sjtug
      VECTOR_SERVER: ci
    volumes:
      - "./caddy/repositories.local.csv:/etc/vector/repositories.csv:ro"
  git-backend:
    build:
      args:
        - USE_GOPROXY=false
  lug:
    build:
      args:
        - USE_SJTUG=false
        - CI=true
    volumes:
      - "./lug/config.local.yaml:/config.local.yaml:ro"
    command: -c /config.local.yaml
  rsync-gateway:
    build:
      args:
        - USE_SJTUG=false
  mirror-intel:
    build:
      args:
        - USE_SJTUG=false
  rsyncd:
    build:
      args:
        - USE_SJTUG=false
