bind = [ "0.0.0.0:8000",]

[endpoints.raspberry-pi-os-images]
redis = "redis://redis/"
redis_namespace = "raspberry-pi-os-images"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/raspberry-pi-os-images"

[endpoints.opencloudos]
redis = "redis://redis/"
redis_namespace = "opencloudos"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/opencloudos"
