bind = [ "0.0.0.0:8000",]

[endpoints.raspberry-pi-os-images]
redis = "redis://redis/"
redis_namespace = "raspberry-pi-os-images"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/raspberry-pi-os-images"

[endpoints.opencloudos]
redis = "redis://redis/"
redis_namespace = "opencloudos"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/opencloudos"

[endpoints.qt]
redis = "redis://redis/"
redis_namespace = "qt"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/qt"

[endpoints.debian-cd]
redis = "redis://redis/"
redis_namespace = "debian-cd"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/debian-cd"

[endpoints.deepin-cd]
redis = "redis://redis/"
redis_namespace = "deepin-cd"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/deepin-cd"

[endpoints.docker-ce]
redis = "redis://redis/"
redis_namespace = "docker-ce"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/docker-ce"

[endpoints.linuxmint-cd]
redis = "redis://redis/"
redis_namespace = "linuxmint-cd"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/linuxmint-cd"

[endpoints.ubuntu-cloud-images]
redis = "redis://redis/"
redis_namespace = "ubuntu-cloud-images"
s3_website = "https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/rsync/ubuntu-cloud-images"
