bind = [ "0.0.0.0:8000",]
s3_url = "https://s3.jcloud.sjtu.edu.cn"
s3_region = "sjtug"
database_url = "postgres://rsync-sjtug@postgres/rsync-sjtug"

[log]
format = "json"
target = "tcp://tunnel:5007"

[endpoints.bmclapi]
namespace = "bmclapi"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/bmclapi"

[endpoints.alhp]
namespace = "alhp"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/alhp"

[endpoints.nspawn]
namespace = "nspawn"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/nspawn"

[endpoints.anthon]
namespace = "anthon"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/anthon"

[endpoints.leopardsh]
namespace = "leopardsh"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/leopardsh"

[endpoints.endeavouros]
namespace = "endeavouros"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/endeavouros"

[endpoints.debian-cdimage]
namespace = "debian-cdimage"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/debian-cdimage"

[endpoints.packman]
namespace = "packman"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/packman"

[endpoints.raspberry-pi-os-images]
namespace = "raspberry-pi-os-images"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/raspberry-pi-os-images"

[endpoints.opencloudos]
namespace = "opencloudos"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/opencloudos"

[endpoints.qt]
namespace = "qt"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/qt"

[endpoints.debian-cd]
namespace = "debian-cd"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/debian-cd"

[endpoints.deepin-cd]
namespace = "deepin-cd"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/deepin-cd"

[endpoints.docker-ce]
namespace = "docker-ce"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/docker-ce"

[endpoints.linuxmint-cd]
namespace = "linuxmint-cd"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/linuxmint-cd"

[endpoints.openkylin]
namespace = "openkylin"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/openkylin"

[endpoints.openkylin-cdimage]
namespace = "openkylin-cdimage"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/openkylin-cdimage"

[endpoints.mx-packages]
namespace = "mx-packages"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/mx-packages"

[endpoints.bioconductor]
namespace = "bioconductor"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/bioconductor"

[endpoints.ubuntu-cloud-images]
namespace = "ubuntu-cloud-images"
s3_bucket = "899a892efef34b1b944a19981040f55b-oss01"
s3_prefix = "rsync/ubuntu-cloud-images"
