base: https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/anaconda/pkgs
repos:
  - main/noarch
  - main/linux-64
  - main/linux-32
  - main/linux-armv6l
  - main/linux-armv7l
  - main/linux-ppc64le
  - main/osx-64
  - main/osx-32
  - main/win-64
  - main/win-32
  - free/noarch
  - free/linux-64
  - free/linux-32
  - free/linux-armv6l
  - free/linux-armv7l
  - free/linux-ppc64le
  - free/osx-64
  - free/osx-32
  - free/win-64
  - free/win-32
  - r/noarch
  - r/linux-64
  - r/linux-32
  - r/linux-armv6l
  - r/linux-armv7l
  - r/linux-ppc64le
  - r/osx-64
  - r/osx-32
  - r/win-64
  - r/win-32
  - msys2/noarch
  - msys2/linux-64
  - msys2/linux-32
  - msys2/osx-64
  - msys2/win-64
  - msys2/win-32
  - pro/noarch
  - pro/linux-64
  - pro/linux-32
  - pro/linux-armv6l
  - pro/linux-armv7l
  - pro/linux-ppc64le
  - pro/osx-64
  - pro/osx-32
  - pro/win-64
  - pro/win-32
  - mro/noarch
  - mro/linux-64
  - mro/linux-32
  - mro/linux-armv6l
  - mro/linux-armv7l
  - mro/linux-ppc64le
  - mro/osx-64
  - mro/osx-32
  - mro/win-64
  - mro/win-32
