[security]
disable_initial_admin_creation = true

[auth.github]
enabled = true
allow_sign_up = true
client_id = ${GITHUB_CLIENT_ID}
client_secret = $__file{/run/secrets/github_client_secret}
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
# @sjtug/mirrors-maintainer
team_ids = 3157357
allowed_organizations = sjtug
role_attribute_path = 'Admin'

[users]
auto_assign_org = true
auto_assign_org_role = Admin
